name: hello-world

on: push

jobs:
  hello-world-job:
  
    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - run: |
          #Testing GitHub Action scripts
          #Enable aliases on github worker
          shopt -s expand_aliases
          echo "$(cat hello_world.txt)"
          mkdir dirtest
          cd dirtest
          touch aaa.txt
          cd ..
          #tree
          alias ll="ls"
          ll
          echo "Pipeline ended"
      - run: echo "test una línea"